In [33]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

for el in range(len(arr)):
    if arr[el] % 2 != 0:
        arr[el] = -1
print(f'1. {arr}')

1. [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [37]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, -1)
print(f'2. arr_1d = {arr_1d}')
print(f'2. arr_2d = {arr_2d}')

2. arr_1d = [1 2 3 4 5 6]
2. arr_2d = [[1 2 3]
 [4 5 6]]


In [53]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5, 6], [7, 8, 9]])
ab = np.vstack((a, b))
print(f'3. {ab}')

3. [[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]


In [57]:
a = np.array([1,2,3])
repeated = np.repeat(a, 3)
tiled = np.tile(a, 3)
output = np.concatenate((repeated, tiled))
print(f'4. Output: {output}')

4. Output: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [59]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

intersected = np.intersect1d(a, b)

print(f'5. {intersected}')

5. [2 4]


In [128]:
np.random.seed(100) 
a = np.random.uniform(1,50, 20)
print(a)
sorted_a = np.argsort(a)[-5:][::-1]

print(f'6. {sorted_a}')

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
6. [15 10  3  7 18]


In [150]:
c=np.array([1,2,3,np.nan,5,6,7,np.nan])
print(c)

c_cleaned = c[~np.isnan(c)]
print(f'7. {c_cleaned}')

[ 1.  2.  3. nan  5.  6.  7. nan]
[1. 2. 3. 5. 6. 7.]


In [152]:
a = np.array([1,2,3,4,5]) 
b = np.array([4,5,6,7,8])

distance = np.linalg.norm(a - b)
print(f'8. {distance}')

8. 6.708203932499369


In [158]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices_of_ones = np.where(x == 1)[0]
fifth_occurrence_index = indices_of_ones[4]
print(f'9. {fifth_occurrence_index}')

9. 8


In [162]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)
result = np.zeros_like(a, dtype=bool)
counts = {}
for i, val in enumerate(a):
    if val in counts:
        counts[val] += 1
        result[i] = True
    else:
        counts[val] = 1

print(f'10. {result}')

[0 0 3 0 2 4 2 2 2 2]
10. [False  True False  True False False  True  True  True  True]
