In [244]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(f'1. {a}')

1. [ 1  2  3  4  5  6  7  8  9 10]


In [246]:
b = np.zeros((3, 3), dtype=int)
print(f'2. {b}')

2. [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [248]:
rng = np.random.default_rng(123)
c = rng.integers(low=1, high=10, size=[5, 5])
print(f'3. {c}')

3. [[1 7 6 1 9]
 [2 3 2 4 2]
 [4 8 5 9 5]
 [3 8 8 8 9]
 [1 5 3 3 3]]


In [250]:
d = np.random.random((4, 4))
print(f'4. {d}')

4. [[0.59601738 0.40427912 0.46617495 0.42734892]
 [0.73051291 0.30904557 0.34905994 0.35029707]
 [0.76557633 0.85593609 0.93422693 0.03097996]
 [0.33596277 0.51519398 0.14002983 0.56947883]]


In [252]:
e = rng.integers(low=1, high=10, size=5)
f = rng.integers(low=1, high=10, size=5)
print(f'5. e = {e}')
print(f'5. f = {f}')
print(f'5. e + f = {e+f}')
print(f'5. e - f = {e-f}')
print(f'5. e * f = {e*f}')

5. e = [8 8 2 4 7]
5. f = [2 6 4 9 7]
5. e + f = [10 14  6 13 14]
5. e - f = [ 6  2 -2 -5  0]
5. e * f = [16 48  8 36 49]


In [254]:
g = np.random.random(7)
h = np.random.random(7)
gh = np.dot(g, h)
print(f'6. g = {g}')
print(f'6. h = {h}')
print(f'6. gh = {gh}')

6. g = [0.27395143 0.29786239 0.70342868 0.8721752  0.04686395 0.44659695
 0.01327234]
6. h = [0.84598085 0.1861877  0.65787559 0.10920209 0.50956351 0.99709474
 0.36287927]
6. gh = 1.3192237667906106


In [258]:
j = rng.integers(low=1, high=10, size=[2, 2])
k = rng.integers(low=1, high=10, size=[2, 3])
print(f'7. j = {j}')
print(f'7. k = {k}')
jk = np.dot(j, k)
print(f'7. jk = {jk}')

7. j = [[3 8]
 [8 2]]
7. k = [[5 8 3]
 [3 2 1]]
7. jk = [[39 40 17]
 [46 68 26]]


In [260]:
l = rng.integers(low=1, high=10, size=[3, 3])
print(f'8. l = {l}')
lt = l.T
print(f'8. lt = {lt}')

8. l = [[5 1 6]
 [4 2 4]
 [1 2 5]]
8. lt = [[5 4 1]
 [1 2 2]
 [6 4 5]]


In [262]:
m = np.random.random((4, 4))
print(f'9. m = {m}')
mt = m.T
print(f'9. mt = {mt}')

9. m = [[0.67984    0.98935098 0.03054429 0.19616457]
 [0.41409212 0.37623697 0.86708555 0.7480667 ]
 [0.87524755 0.78084044 0.94053369 0.48720319]
 [0.0550338  0.57221543 0.62117415 0.11464171]]
9. mt = [[0.67984    0.41409212 0.87524755 0.0550338 ]
 [0.98935098 0.37623697 0.78084044 0.57221543]
 [0.03054429 0.86708555 0.94053369 0.62117415]
 [0.19616457 0.7480667  0.48720319 0.11464171]]


In [264]:
n = rng.integers(low=1, high=10, size=[3, 4])
o = rng.integers(low=1, high=10, size=4)
print(f'10. n = {n}')
print(f'10. o = {o}')
print(f'10. n*o = {n*o}')

10. n = [[1 7 3 9]
 [2 6 5 9]
 [6 8 5 2]]
10. o = [2 8 2 7]
10. n*o = [[ 2 56  6 63]
 [ 4 48 10 63]
 [12 64 10 14]]


In [266]:
p = np.random.random((2, 3))
q = np.random.random(3)
print(f'11. p = {p}')
print(f'11. q = {q}')
print(f'11. p*q = {p*q}')

11. p = [[0.63052111 0.9877574  0.11812914]
 [0.41531051 0.28758545 0.46775518]]
11. q = [0.40983329 0.76435375 0.91069102]
11. p*q = [[0.25840854 0.75499607 0.10757914]
 [0.17020808 0.21981701 0.42598044]]


In [268]:
r = rng.integers(low=1, high=10, size=[2, 2])
s = rng.integers(low=1, high=10, size=[2, 2])
print(f'12. r = {r}')
print(f'12. s = {s}')
print(f'12. r*s = {r*s}')

12. r = [[5 3]
 [4 8]]
12. s = [[5 8]
 [9 3]]
12. r*s = [[25 24]
 [36 24]]


In [270]:
t = rng.integers(low=1, high=10, size=[2, 2])
u = rng.integers(low=1, high=10, size=[2, 2])
tu = np.dot(t, u)
print(f'13. t = {t}')
print(f'13. u = {u}')
print(f'13. tu = {tu}')


13. t = [[5 5]
 [5 1]]
13. u = [[4 6]
 [9 3]]
13. tu = [[65 45]
 [29 33]]


In [272]:
v = rng.integers(low=1, high=100, size=[5, 5])
print(f'14. v = {v}')
v = v.sum()
print(f'14. v.sum() = {v}')

14. v = [[64 76 92 18 67]
 [31 44  2 72  4]
 [38 50 67 47 84]
 [13 26 26 38  1]
 [43 38 58 58 28]]
14. v.sum() = 1085


In [274]:
w = rng.integers(low=1, high=10, size=[4, 4])
x = rng.integers(low=1, high=10, size=[4, 4])
print(f'15. w = {w}')
print(f'15. x = {x}')
print(f'15. w-x = {w-x}')

15. w = [[4 5 8 1]
 [6 1 3 4]
 [8 4 5 6]
 [7 4 6 8]]
15. x = [[4 9 4 4]
 [1 5 5 4]
 [6 5 9 4]
 [4 8 5 3]]
15. w-x = [[ 0 -4  4 -3]
 [ 5 -4 -2  0]
 [ 2 -1 -4  2]
 [ 3 -4  1  5]]


In [276]:
y = np.random.random((3, 3))
print(f'16. y = {y}')
z = np.array((y[0].sum(), y[1].sum(), y[2].sum()))
print(f'16. z = {z}')

16. y = [[0.69697735 0.06000238 0.65528251]
 [0.53542467 0.70853381 0.3825798 ]
 [0.20208623 0.58749509 0.48116002]]
16. z = [1.41226224 1.62653828 1.27074134]


In [278]:
aa = rng.integers(low=1, high=10, size=[3, 4])
print(f'17. aa = {aa}')
ab = aa.copy()**2
print(f'17. ab = {ab}')

17. aa = [[5 5 4 5]
 [6 9 1 9]
 [5 4 6 2]]
17. ab = [[25 25 16 25]
 [36 81  1 81]
 [25 16 36  4]]


In [280]:
ac = rng.integers(low=1, high=50, size=4)
print(f'18. ac = {ac}')
ad = np.sqrt(ac)
print(f'18. ad = {ad}')

18. ac = [37  5 22 10]
18. ad = [6.08276253 2.23606798 4.69041576 3.16227766]
